1 dimension


In [ ]:
import numpy as np
A = np.array([1,2,3])
print(A)
#[1 2 3]
print(type(A))
#[1 2 3]
print(np.zeros(7))
#[0. 0. 0. 0. 0. 0. 0.]
print(np.ones(12))
#[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
print(np.empty(3).size)
#np.empty create an array but dont assign  value
print(np.arange(10,dtype= float))
#[0 1 2 3 4 5 6 7 8 9]
print(np.arange(10,20))
#[10 11 12 13 14 15 16 17 18 19]
print(np.arange(10,20,3))
#[10 13 16 19]
print(np.linspace(0,10,5))
#[ 0.   2.5  5.   7.5 10. ]
print(np.asarray(A)) # copy
#[1 2 3]
print(np.ones_like(A)) 
#create an nd array same as a but value are all one
#[1 1 1] 
print(np.zeros_like(A)) 
#create an nd array same as a but value are all zero
#[0 0 0] 
print(np.empty(A)) 
#create an nd array same as a but value are all empty
print(np.full(5,8))
#[8 8 8 8 8]
print(np.random.random((2,3)))
#[[0.57281141 0.98874283 0.44597598]
 #[0.0412086  0.64839552 0.04160949]]

<h1 style = "color:#FFFF00;font-style: italic;font-weight:500;">
	np.random.randint(low,high = None,size = None,dtype = int)
</h1>
<h3>
    low:the smallest
</h3>
<h3>
    high: if exist, the biggest. otherwise values will betweem 0 ~low
</h3>
<h3>
    size: dimension
</h3>
<h3>
    dtype: type of values
</h3>

In [4]:
import numpy as np

A = np.random.randint(10, 20)
print(A)
# one of 10~19, ex:14

B  =np.random.randint(0,30,10)
print(B)
# ex: [ 5  0 18  3  9  8 28 28 17 22]

C = np.random.randint(10,size=(3,5))
print(C)
#[[7 9 7 8 5]
# [3 3 4 0 6]
# [3 0 3 0 6]]

11
[21 16 12  3 28 22 13 11 29  4]
[[7 9 7 8 5]
 [3 3 4 0 6]
 [3 0 3 0 6]]


<h1 style = "color:#FFFF00;font-style: italic;font-weight:500;">
	np.arange(start,stop,step = 1)
</h1>
<h3>

</h3>

In [9]:
import numpy as np
A = np.arange(8)
print(A)
#[0 1 2 3 4 5 6 7]
B = np.arange(1,10)
print(B)
#[1 2 3 4 5 6 7 8 9]
C = np.arange(1,11,3)
print(C)
#[1 4 7 10]

[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]
[ 1  4  7 10]


<h1 style = "color:#FFFF00;font-style: italic;font-weight:500;">
	np.linspace(start,end(included),num)
</h1>
<h3>

</h3>

In [1]:
import numpy as np
A = np.linspace(0,2,10)
print(A)
#[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111 1.33333333 1.55555556 1.77777778 2.        ]

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


<h1 style = "color:#FFFF00;font-style: italic;font-weight:500;">
    Reshape
</h1>
<h1 style = "color:#FFFF00;font-style: italic;font-weight:500;">
    np.reshape(arr,newshape)
</h1>
<h3>

</h3>

In [8]:
import numpy as np;
A = np.arange(16)
print(A)
#[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
print(np.reshape(A,(2,8)))
#[[ 0  1  2  3  4  5  6  7]
#[ 8  9 10 11 12 13 14 15]]
print(np.reshape(A,(2,-1)))
#[[ 0  1  2  3  4  5  6  7]
#[ 8  9 10 11 12 13 14 15]]
print(np.reshape(A,(4,-1)))
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]
# [12 13 14 15]]
print(np.reshape(A,(-1,4)))
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]
# [12 13 14 15]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


2 dimension


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [1, 2, 3]])
print(A.shape)
#(2,3)
print(A.size)
#6
print(A.sum())

print(np.empty((3,2)))
#[[0. 0.]
#[0. 0.]
#[0. 0.]]
print(np.zeros([2,3]))
print(np.ones([2,3]))
#[[0. 0. 0.]
# [0. 0. 0.]]
print(np.eye(3))
#print(np.identity(3))
#[[1. 0. 0.]
# [0. 1. 0.]
# [0. 0. 1.]]


3 dimension

In [1]:
import numpy as np
print(np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
]   
))
#3*2*3
print(np.empty([3,1,2]))
print(np.ones([2,2,2]))
print(np.zeros([1,1,4]))


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[-8.44319057e-312 -6.71836014e-257]]

 [[ 8.44319602e-312  8.44319602e-312]]

 [[ 5.43472210e-323  2.47032823e-323]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[0. 0. 0. 0.]]]


high dimension

In [ ]:
print(np.array([
    [
        [1,1],
        [2,2]   
    ]
]))
print(np.ones([2,1,1,2]))
