<h1 style = "color:#FFFF00;font-style: italic;font-weight:500;">
arr.ndim
</h1>
<h3>
    can know the dimension of the array
</h3>

In [6]:
import numpy as np
arr0 = np.array([1,2,3,4])
print(arr0.ndim)
#1
arr1 = np.array([[1,2],[2,3]])
print(arr1.ndim)
#2
arr2 = np.ones([4,3,1,5,2,4,5])
print(arr2.ndim)
#7

1
2
7


<h1 style = "color:#FFFF00">
I/O
</h1>

In [6]:
import numpy as np
ori = np.array([1,2,3])
np.save("my_array",ori)
# it will be at .npy document
np.savetxt('my_array.txt', ori)
array_from_npy = np.load('my_array.npy')
print(array_from_npy)
array_from_txtfile = np.loadtxt('my_array.txt')
print(array_from_txtfile)


[1 2 3]
[1. 2. 3.]


<h1 style = "color:#FFFF00">
data type (dtype)
<h3>
    <img src = "./picture/numpy_dtype.png"/>
</h3>

In [14]:
import numpy as np
A = np.array([1.2,3.7,5.4],dtype="int8")
print(A)
#[1 3 5]
B = np.array([-1.4,-5,9],dtype = "uint8")
print(B)
#[255 251   9]
x = np.float32([1.5,35.3,93])
print(x)
#[ 1.5 35.3 93. ]
x = np.int_(x)
print(x)
#[ 1 35 93]


[1 3 5]
[255 251   9]
[ 1.5 35.3 93. ]
[ 1 35 93]


<h1 style = "color:#FFFF00">

</h1>
<h3>
    
</h3>

<h1 style = "color:#FFFF00">

</h1>
<h3>
    
</h3>

<h1 style = "color:#FFFF00">

</h1>
<h3>
    
</h3>

<h1 style = "color:#FFFF00">

</h1>
<h3>
    
</h3>

<h1 style = "color:#FFFF00">

</h1>
<h3>
    
</h3>