<h1 style = "color:#FFFF00">
add
<h3>
  
</h3>

In [2]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = A+B
print(C)
print(np.add(A,B))
#[5 7 9]

[5 7 9]
[5 7 9]


<h1 style = "color:#FFFF00">
subtract
<h3>
  
</h3>

In [3]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = A-B
print(C)
print(np.subtract(A,B))
#[-3 -3 -3]


[-3 -3 -3]
[-3 -3 -3]


<h1 style = "color:#FFFF00">
multiply
<h3>
  
</h3>

In [4]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = A *B 
print(C)
print(np.multiply(A,B))
#[4 10 18]


[ 4 10 18]
[ 4 10 18]


<h1 style = "color:#FFFF00">
divide
<h3>
  
</h3>

In [5]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
C = A/B
print(C)
print(np.divide(A,B))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


<h1 style = "color:#FFFF00">
other math
<h3>
  
</h3>

In [16]:
import numpy as np
A = np.array([-1,2,-3])
B = np.array([4,9,25])
print(np.abs(A))
print(np.absolute(A))
#[1 2 3]

print(np.sqrt(B))
#[2. 3. 5.]
print(np.log(B))
#[1.38629436 2.19722458 3.21887582]
print(np.cos(A))
#[ 0.54030231 -0.41614684 -0.9899925 ]
print(np.sin(A))
#[-0.84147098  0.90929743 -0.14112001]
print(np.arctan(A))
#[-0.78539816  1.10714872 -1.24904577]

[1 2 3]
[1 2 3]
[2. 3. 5.]
[1.38629436 2.19722458 3.21887582]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-0.84147098  0.90929743 -0.14112001]
[-0.78539816  1.10714872 -1.24904577]


<h1 style = "color:#FFFF00">
comparision
<h1>
<h3>
  
</h3>

In [1]:
import numpy as np
A = np.array([1,5,9])
B = np.array([4,5,6])
print(A>B)
#[False False  True]
print(A==B)
#[False  True False]
print(A<B)
#[ True False False]


[False False  True]
[False  True False]
[ True False False]


<h1 style = "color:#FFFF00">
add
<h3>
  
</h3>

In [ ]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])


<h1 style = "color:#FFFF00">
add
<h3>
  
</h3>

In [ ]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])


<h1 style = "color:#FFFF00">
add
<h3>
  
</h3>

In [ ]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
