numpy allows us to us efficient vector and matrix 


In [5]:
import numpy

A = numpy.array([1,2,3])
B = numpy.array((4,5,6))
#create an array with list or tuple

print(A)
#[1 2 3]
print(B)
#[4 5 6]
print(type(A))
#print(type(B))
#<class 'numpy.ndarray'>
A[0] = 7
print(A)
#[7 2 3]


[1 2 3]
[4 5 6]
<class 'numpy.ndarray'>
[7 2 3]


create an array with only 0 or 1 can use .zeros or .ones

In [4]:
import numpy as np

print(np.zeros(7))
#[0. 0. 0. 0. 0. 0. 0.]
print(np.ones(12))
#[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
print(np.empty(3).size)
#np.empty create an array but dont assign  value
print(np.arange(10))
#[0 1 2 3 4 5 6 7 8 9]
print(np.arange(10,20,3))
#[10 13 16 19]

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
3
[0 1 2 3 4 5 6 7 8 9]
[10 13 16 19]


get value from index


In [ ]:
A = numpy.array([11,12,13])

print(A[0])
#11
print(A[0:2])
#[11 12]
mask =(A % 4 == 0 )
print(mask)
#[False  True False
print(A[mask])
#[12]

array counting

array size have two be correct

multiply of array is the same position to multiply


In [17]:
import numpy as np

A = numpy.array([1,2,3])
B = numpy.array((4,5,6))

result1 = A+B
print(result1)
#[5 7 9]
result2 = B-A
print(result2)
#[3 3 3]
result3 =A*B
print(result3)
#[4 10 18]
result4 =A/B
print(result4)
#[0.25 0.4 0.5]

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


two demision


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [1, 2, 3]])
print(np.empty([3,2]))
#[[0. 0.]
#[0. 0.]
#[0. 0.]]
print(np.zeros([2,3]))
print(np.ones([2,3]))
#[[0. 0. 0.]
# [0. 0. 0.]]

3 dimension


In [11]:
print(np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
]   
))
#3*2*3
print(np.empty([3,1,2]))
print(np.ones([2,2,2]))
print(np.zeros([1,1,4]))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[0.14285714 0.25      ]]

 [[0.33333333 4.        ]]

 [[2.5        2.        ]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[0. 0. 0. 0.]]]


counting

In [9]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [1, 2, 3]])


result1 = A+B
print(result1)
#[[ 8 10 12]
#[ 5  7  9]]
result2 = B-A
print(result2)
#[[ 6  6  6]
#[-3 -3 -3]]
result3 =A*B
print(result3)
#[[ 7 16 27]
#[ 4 10 18]]
result4 =A/B
print(result4)
#[[0.14285714 0.25       0.33333333]
#[4.         2.5        2.        ]]



[[0.14285714 0.25      ]
 [0.33333333 4.        ]
 [2.5        2.        ]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[ 8 10 12]
 [ 5  7  9]]
[[ 6  6  6]
 [-3 -3 -3]]
[[ 7 16 27]
 [ 4 10 18]]
[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]


Transpose

In [4]:
import numpy as np

A = np.array([[1,2],[3,4]])
print(A)
# 1 2 
# 3 4
print(A.T)
# 1 3
# 2 4 



[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


dot product ( matrix multiply ) 

In [5]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
#2*3
B = np.array([[7, 8, 9], [1, 2, 3], [1, 2, 3]])
#3*3
result_1 = A.dot(B)
#2*3
print(result_1)
# [[12 18 24]
#  [39 54 69]]

[[12 18 24]
 [39 54 69]]


inner product
ABT

In [13]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[3, 4, 5], [1, 1, 1]])


result1 = np.inner(A,B)
result2 = A.dot(B.T)
print(result1)
print(result2)
#[[26  6]
# [62 15]]


[2. 4. 6.]
[[26  6]
 [62 15]]
[[26  6]
 [62 15]]


outer product

In [14]:
import numpy as np

A = np.array([[1,2,3],[2,1,0],[4,5,3]])
B = np.array([[4,1,3],[3,2,0],[1,5,3]])

result1 = np.outer(A,B)

print(result1)


[[ 4  1  3  3  2  0  1  5  3]
 [ 8  2  6  6  4  0  2 10  6]
 [12  3  9  9  6  0  3 15  9]
 [ 8  2  6  6  4  0  2 10  6]
 [ 4  1  3  3  2  0  1  5  3]
 [ 0  0  0  0  0  0  0  0  0]
 [16  4 12 12  8  0  4 20 12]
 [20  5 15 15 10  0  5 25 15]
 [12  3  9  9  6  0  3 15  9]]
